Create BEIR benchmark doc
NomaDamas/RAGchain-docs pull request #27
Opened 2023-12-26 07:32 UTC by minsing-jin

close #26

2023-12-26 07:52 UTC, vkehfdl1 requested changes

2023-12-26 07:52 UTC, vkehfdl1 commented on ragchain-structure/benchmark/dataset-evaluator/beir.md
> +We except context_recall metric that is ragas metric.
We do not support context_recall metric, which is from `ragas`.

2023-12-26 07:52 UTC, vkehfdl1 commented on ragchain-structure/benchmark/dataset-evaluator/beir.md
> +evaluator.ingest(retrievals=[retrieval], db=db, ingest_size=20) # ingest dataset to db and retrievals
[retrieval] => retrievals

2023-12-26 07:52 UTC, vkehfdl1 commented on ragchain-structure/benchmark/dataset-evaluator/beir.md
> +remove_path(bm25_path, pickle_path)
delete this code
No need for tutorial, and only need for pytest fixture;;

2023-12-26 07:52 UTC, vkehfdl1 commented on ragchain-structure/benchmark/dataset-evaluator/beir.md
> +retrieval, db, llm, pipeline = set_beir_evaluator(bm25_path, pickle_path)
also, where is set_beir_evaluator?
Don't just copy and paste pytest fixture codes. Write adequate code for newbies.

2023-12-26 07:52 UTC, vkehfdl1 commented on ragchain-structure/benchmark/dataset-evaluator/beir.md
> +in each dataset.
useless annotation

2023-12-26 07:52 UTC, vkehfdl1 commented on ragchain-structure/benchmark/dataset-evaluator/beir.md
> +set others in `set_beir_evaluator`.
You didn't make generate_path and set_beir_evaluator function for BeirEvaluator. Usage of BeirEvaluator is literally same with other evaluator, right?
You dind't read this AI generated documentation, right?

2024-01-05 02:15 UTC, minsing-jin commented
All pull requests about benchmark docs are unified in issue #24.

2024-01-05 02:15 UTC, closed without merging